---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[preview_prod::default]
    attributes:
      preview_prod:
        node_id: testnode1
        cassandra_hosts: ["localhost"]
        edge_host: "http://localhost"
        s3Key: foo
        s3Secret: bar
        s3Buckets: ["bucketa"]