---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[preview_prod::default]
    attributes:
      preview_prod:
        node_id: testnode1
        cassandra_hosts: ["localhost"]
        edge_host: "http://localhost"
        s3Key: ""
        s3Secret: ""
        s3Buckets: ["bucketa"]
        s3Host: "http://localhost:9444/"
        cacheS3Buckets: ["bucketb"]
        tramHosts: ["localhost:7040"]
        proxyApps:
          local: 127.0.0.1
